/**
 * File: AddClient.java
 * Date: April 16, 2020
 * @Author: Nour Debiat, Rebekah Qu
 * Purpose: This window allows the user to add new clients.
 */
package vetportal;

import javax.swing.*;
import java.awt.*;
import javax.swing.text.MaskFormatter;
import java.text.ParseException;

public class AddClient extends JFrame {

    //Creating VetPortal object:
    VetPortal vetPortal;

    /**
     * Creates new form AddClient
	 * @param vetPortal
     * @throws ParseException
     */
    public AddClient(VetPortal vetPortal) throws ParseException {
        super("Add New Client Form");
        this.vetPortal = vetPortal;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() throws ParseException {

        addClientPanel = new JPanel();
        cancelBtn = new JButton();
        submitBtn = new JButton();
        addClientLabel = new JLabel();
        firstNameLabel = new JLabel();
        lastNameLabel = new JLabel();
        emailLabel = new JLabel();
        phoneLabel = new JLabel();
        firstNameField = new JTextField();
        lastNameField = new JTextField();
        emailField = new JTextField();
        MaskFormatter phoneFormat = new MaskFormatter("(###) ###-####");
        phoneField = new JFormattedTextField(phoneFormat);
        cWarningMsg = new JLabel();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        addClientPanel.setBackground(new Color(255, 255, 255));

        cancelBtn.setBackground(new Color(255, 255, 255));
        cancelBtn.setFont(new Font("Calibri", 1, 18)); // NOI18N
		cancelBtn.setForeground(new Color(122, 188, 255));
        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(event -> cancel());

        submitBtn.setBackground(new Color(255, 255, 255));
        submitBtn.setFont(new Font("Calibri", 1, 18)); // NOI18N   
		submitBtn.setForeground(new Color(122, 188, 255));		
        submitBtn.setText("Submit");
        submitBtn.addActionListener(event -> submit());
        
        addClientLabel.setBackground(new Color(255, 255, 255));
        addClientLabel.setFont(new Font("Calibri", 0, 20)); // NOI18N
        addClientLabel.setHorizontalAlignment(SwingConstants.CENTER);
        addClientLabel.setText("<html>Fill out for the form below to add a new client <br>or cancel to return to the Clients Dashboard</html>");

        firstNameLabel.setFont(new Font("Calibri", 0, 18)); // NOI18N
        firstNameLabel.setText("First Name");

        lastNameLabel.setFont(new Font("Calibri", 0, 18)); // NOI18N
        lastNameLabel.setText("Last Name");

        emailLabel.setFont(new Font("Calibri", 0, 18)); // NOI18N
        emailLabel.setText("Email");

        phoneLabel.setFont(new Font("Calibri", 0, 18)); // NOI18N
        phoneLabel.setText("Phone Number");

        firstNameField.setFont(new Font("Calibri", 0, 18)); // NOI18N

        lastNameField.setFont(new Font("Calibri", 0, 18)); // NOI18N

        emailField.setFont(new Font("Calibri", 0, 18)); // NOI18N

        phoneField.setFont(new Font("Calibri", 0, 18)); // NOI18N

        cWarningMsg.setFont(new Font("Calibri", 0, 14)); // NOI18N
        cWarningMsg.setForeground(new Color(203, 0, 0));
        cWarningMsg.setHorizontalAlignment(SwingConstants.CENTER);

        GroupLayout addClientPanelLayout = new GroupLayout(addClientPanel);
        addClientPanel.setLayout(addClientPanelLayout);
        addClientPanelLayout.setHorizontalGroup(
            addClientPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(addClientPanelLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(addClientPanelLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addComponent(lastNameLabel)
                    .addComponent(firstNameLabel)
                    .addComponent(emailLabel)
                    .addComponent(phoneLabel))
                .addGap(18, 18, 18)
                .addGroup(addClientPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(firstNameField, GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(lastNameField)
                    .addComponent(emailField)
                    .addComponent(phoneField, GroupLayout.Alignment.TRAILING))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(GroupLayout.Alignment.TRAILING, addClientPanelLayout.createSequentialGroup()
                .addGap(0, 36, Short.MAX_VALUE)
                .addComponent(addClientLabel, GroupLayout.PREFERRED_SIZE, 478, GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
            .addGroup(addClientPanelLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(submitBtn)
                .addGap(110, 110, 110)
                .addComponent(cancelBtn)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(GroupLayout.Alignment.TRAILING, addClientPanelLayout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cWarningMsg, GroupLayout.PREFERRED_SIZE, 385, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        addClientPanelLayout.setVerticalGroup(
            addClientPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(addClientPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(addClientLabel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(addClientPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameLabel)
                    .addComponent(firstNameField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addClientPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(lastNameLabel)
                    .addComponent(lastNameField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addClientPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(emailField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailLabel))
                .addGap(18, 18, 18)
                .addGroup(addClientPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneLabel)
                    .addComponent(phoneField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(cWarningMsg, GroupLayout.PREFERRED_SIZE, 46, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(addClientPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(submitBtn)
                    .addComponent(cancelBtn))
                .addContainerGap(94, Short.MAX_VALUE))
        );

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(addClientPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(addClientPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Event for Submit button click
    private void submit() {
        // Attempt to create a new client
        createNewClient();
    }

    // Event for Cancel button click
    private void cancel() {
	// Close the Add Client window and do nothing
        dispose();
    }

    private void createNewClient() {
        Boolean createTF = vetPortal.createClient(cWarningMsg, firstNameField.getText(), lastNameField.getText(), phoneField.getText(), emailField.getText());

        // If creation was successful
        if(createTF) {
            // If success, reset the form
            firstNameField.setText(null);
            lastNameField.setText(null);
            emailField.setText(null);
            phoneField.setText(null);
            // And close it
            dispose();
        } 
	// If creation was not successful, cWarningMsg will convey any errors to the user

	// Refresh the Clients Table in the Dashboard
        DashboardsGui dashboard = vetPortal.getDashboard();
        DashboardsGui.MyClientTableModel model = (DashboardsGui.MyClientTableModel) dashboard.getClientTable().getModel();
        model.refetchClients();       
    } //end of createNewClient()

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JLabel addClientLabel;
    private JPanel addClientPanel;
    private JLabel cWarningMsg;
    private JButton cancelBtn;
    private JTextField emailField;
    private JLabel emailLabel;
    private JTextField firstNameField;
    private JLabel firstNameLabel;
    private JTextField lastNameField;
    private JLabel lastNameLabel;
    private JTextField phoneField;
    private JLabel phoneLabel;
    private JButton submitBtn;
    // End of variables declaration//GEN-END:variables
}
