/**
 * File: ViewClient.java
 * Date: May 1, 2020
 * @Author: Nour Debiat
 * Purpose: This window allows the user to view a Client's information, pets, and appointments.
 */

package vetportal;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import java.awt.*;
import java.util.ArrayList;

public class ViewClient extends JFrame {

    private String clientFirstName, clientLastName, clientEmail, clientPhoneNumber;
    private ArrayList<Pets> allOwnedPets;
    private ArrayList<Appointments> allScheduledAppointments;

    /**
     * Creates new form ViewClient
     * @param allOwnedPets The list of pets the client owns
     * @param allScheduledAppointments The list of appointments the client has
     * @param clientFirstName The client's first name
     * @param clientLastName The client's last name
     * @param clientEmail The client's email address
     * @param clientPhoneNumber The client's phone number
     */
    public ViewClient(ArrayList<Pets> allOwnedPets, ArrayList<Appointments> allScheduledAppointments, String clientFirstName, String clientLastName, String clientEmail, String clientPhoneNumber) {
        super("View Client Information");
        this.allOwnedPets = allOwnedPets;
        this.allScheduledAppointments = allScheduledAppointments;
        this.clientFirstName = clientFirstName;
        this.clientLastName = clientLastName;
        this.clientEmail = clientEmail;
        this.clientPhoneNumber = clientPhoneNumber;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewClientPanel = new JPanel();
        clientInfoTabs = new JTabbedPane();
        clientPanel = new JPanel();
        firstNameLabel = new JLabel();
        firstNameField = new JTextField(clientFirstName);
        lastNameLabel = new JLabel();
        lastNameField = new JTextField(clientLastName);
        emailLabel = new JLabel();
        emailField = new JTextField(clientEmail);
        phoneNumberLabel = new JLabel();
        phoneNumberField = new JTextField(clientPhoneNumber);
        cCloseBtn = new JButton();
        petsPanel = new JPanel();
        cPetScrollPane = new JScrollPane();
        cPetTable = new JTable();
        pCloseBtn = new JButton();
        appointmentsPanel = new JPanel();
        cAppointmentsScrollPane = new JScrollPane();
        cAppointmentsTable = new JTable();
        aCloseBtn = new JButton();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        viewClientPanel.setBackground(new Color(255, 255, 255));
        viewClientPanel.setFont(new Font("Calibri", 0, 18)); // NOI18N

        clientInfoTabs.setBackground(new Color(255, 255, 255));
        clientInfoTabs.setTabPlacement(JTabbedPane.LEFT);
        clientInfoTabs.setFont(new Font("Calibri", 0, 18)); // NOI18N

        clientPanel.setBackground(new Color(255, 255, 255));

        firstNameLabel.setFont(new Font("Calibri", 0, 16)); // NOI18N
        firstNameLabel.setText("First Name");

        firstNameField.setEditable(false);
        firstNameField.setFont(new Font("Calibri", 0, 16)); // NOI18N

        lastNameLabel.setFont(new Font("Calibri", 0, 16)); // NOI18N
        lastNameLabel.setText("Last Name");

        lastNameField.setEditable(false);
        lastNameField.setFont(new Font("Calibri", 0, 16)); // NOI18N

        emailLabel.setFont(new Font("Calibri", 0, 16)); // NOI18N
        emailLabel.setText("Email Address");

        emailField.setEditable(false);
        emailField.setFont(new Font("Calibri", 0, 16)); // NOI18N

        phoneNumberLabel.setFont(new Font("Calibri", 0, 16)); // NOI18N
        phoneNumberLabel.setText("Phone Number");

        phoneNumberField.setEditable(false);
        phoneNumberField.setFont(new Font("Calibri", 0, 16)); // NOI18N

        cCloseBtn.setBackground(new Color(255, 255, 255));
        cCloseBtn.setFont(new Font("Calibri", 0, 18)); // NOI18N
        cCloseBtn.setText("Close");

        GroupLayout clientPanelLayout = new GroupLayout(clientPanel);
        clientPanel.setLayout(clientPanelLayout);
        clientPanelLayout.setHorizontalGroup(
            clientPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(clientPanelLayout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addGroup(clientPanelLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addGroup(clientPanelLayout.createSequentialGroup()
                        .addComponent(phoneNumberLabel)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(phoneNumberField, GroupLayout.PREFERRED_SIZE, 200, GroupLayout.PREFERRED_SIZE))
                    .addGroup(clientPanelLayout.createSequentialGroup()
                        .addComponent(emailLabel)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(emailField, GroupLayout.PREFERRED_SIZE, 200, GroupLayout.PREFERRED_SIZE))
                    .addGroup(clientPanelLayout.createSequentialGroup()
                        .addComponent(lastNameLabel)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lastNameField, GroupLayout.PREFERRED_SIZE, 200, GroupLayout.PREFERRED_SIZE))
                    .addGroup(clientPanelLayout.createSequentialGroup()
                        .addComponent(firstNameLabel)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(firstNameField, GroupLayout.PREFERRED_SIZE, 200, GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(55, Short.MAX_VALUE))
            .addGroup(GroupLayout.Alignment.TRAILING, clientPanelLayout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cCloseBtn)
                .addContainerGap())
        );
        clientPanelLayout.setVerticalGroup(
            clientPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(clientPanelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(clientPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameLabel)
                    .addComponent(firstNameField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(clientPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(lastNameLabel)
                    .addComponent(lastNameField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(clientPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel)
                    .addComponent(emailField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(clientPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneNumberLabel)
                    .addComponent(phoneNumberField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 312, Short.MAX_VALUE)
                .addComponent(cCloseBtn)
                .addContainerGap())
        );

        clientInfoTabs.addTab("Client", clientPanel);

        petsPanel.setBackground(new Color(255, 255, 255));

        cPetScrollPane.setBackground(new Color(255, 255, 255));

        cPetTable.setFont(new Font("Calibri", 0, 14)); // NOI18N
        cPetTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pet Name", "DOB", "Species", "Gender"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        cPetScrollPane.setViewportView(cPetTable);

        pCloseBtn.setBackground(new Color(255, 255, 255));
        pCloseBtn.setFont(new Font("Calibri", 0, 18)); // NOI18N
        pCloseBtn.setText("Close");

        GroupLayout petsPanelLayout = new GroupLayout(petsPanel);
        petsPanel.setLayout(petsPanelLayout);
        petsPanelLayout.setHorizontalGroup(
            petsPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(petsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(petsPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(cPetScrollPane, GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                    .addGroup(GroupLayout.Alignment.TRAILING, petsPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(pCloseBtn)))
                .addContainerGap())
        );
        petsPanelLayout.setVerticalGroup(
            petsPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(petsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cPetScrollPane, GroupLayout.PREFERRED_SIZE, 482, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pCloseBtn)
                .addContainerGap())
        );

        clientInfoTabs.addTab("Pets", petsPanel);

        appointmentsPanel.setBackground(new Color(255, 255, 255));

        cAppointmentsScrollPane.setBackground(new Color(255, 255, 255));

        cAppointmentsTable.setFont(new Font("Calibri", 0, 14)); // NOI18N
        cAppointmentsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Time", "Pet", "Reason"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        cAppointmentsScrollPane.setViewportView(cAppointmentsTable);

        aCloseBtn.setBackground(new Color(255, 255, 255));
        aCloseBtn.setFont(new Font("Calibri", 0, 18)); // NOI18N
        aCloseBtn.setText("Close");

        GroupLayout appointmentsPanelLayout = new GroupLayout(appointmentsPanel);
        appointmentsPanel.setLayout(appointmentsPanelLayout);
        appointmentsPanelLayout.setHorizontalGroup(
            appointmentsPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(appointmentsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(appointmentsPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(cAppointmentsScrollPane, GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                    .addGroup(GroupLayout.Alignment.TRAILING, appointmentsPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(aCloseBtn)))
                .addContainerGap())
        );
        appointmentsPanelLayout.setVerticalGroup(
            appointmentsPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(appointmentsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cAppointmentsScrollPane, GroupLayout.PREFERRED_SIZE, 482, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(aCloseBtn)
                .addContainerGap())
        );

        clientInfoTabs.addTab("Appointments", appointmentsPanel);

        GroupLayout viewClientPanelLayout = new GroupLayout(viewClientPanel);
        viewClientPanel.setLayout(viewClientPanelLayout);
        viewClientPanelLayout.setHorizontalGroup(
            viewClientPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(viewClientPanelLayout.createSequentialGroup()
                .addComponent(clientInfoTabs, GroupLayout.PREFERRED_SIZE, 750, GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        viewClientPanelLayout.setVerticalGroup(
            viewClientPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(clientInfoTabs)
        );

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(viewClientPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(viewClientPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        TableColumnModel columnModel = cPetTable.getColumnModel();
        columnModel.getColumn(1).setPreferredWidth(120);
        DefaultTableModel petModel = (DefaultTableModel)cPetTable.getModel();
        if (allOwnedPets.isEmpty()) {
            String[] emptyFields = {"", "", "", ""};
            petModel.addRow(emptyFields);
        } else {
            for (Pets pet : allOwnedPets) {
                String[] petRow = {pet.getPetName(), pet.getPetDateOfBirth(), pet.getPetSpecies(), pet.getPetGender()};
                petModel.addRow(petRow);
            }
        }

        DefaultTableModel appointmentModel = (DefaultTableModel)cAppointmentsTable.getModel();
        if (allScheduledAppointments.isEmpty()) {
            String[] emptyFields = {"", "", "", ""};
            appointmentModel.addRow(emptyFields);
        } else {
            for (Appointments appointment : allScheduledAppointments) {
                String[] appointmentRow = {appointment.getAptDate(), appointment.getAptTime(), appointment.getPet(), appointment.getAptReason()};
                appointmentModel.addRow(appointmentRow);
            }
        }

        aCloseBtn.addActionListener(event -> close());
        cCloseBtn.addActionListener(event -> close());
        pCloseBtn.addActionListener(event -> close());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Close button function
    private void close() {
        //close the window
        dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton aCloseBtn;
    private JPanel appointmentsPanel;
    private JScrollPane cAppointmentsScrollPane;
    private JTable cAppointmentsTable;
    private JButton cCloseBtn;
    private JScrollPane cPetScrollPane;
    private JTable cPetTable;
    private JTabbedPane clientInfoTabs;
    private JPanel clientPanel;
    private JTextField emailField;
    private JLabel emailLabel;
    private JTextField firstNameField;
    private JLabel firstNameLabel;
    private JTextField lastNameField;
    private JLabel lastNameLabel;
    private JButton pCloseBtn;
    private JPanel petsPanel;
    private JTextField phoneNumberField;
    private JLabel phoneNumberLabel;
    private JPanel viewClientPanel;
    // End of variables declaration//GEN-END:variables
}
